### ISSUE TITLE
Add every Nth minute?

### ISSUE THREAD

**Issue by jsiu22** [arnapou/jqcron#36]
Can we have an every Nth minute? So every 3 (*/3 * * * *) etc?
I've been adding it to my local copy, but it feels a little imperfect.

**Comment by brunobertechini** [comment]
Can you please add this one ?

**Comment by arnapou** [comment]
This issue is really old, and I apologize for not answering, but I have not the time to write that. 
I didn't wrote it 6 years ago because I didn't need it and I still don't need it.
If someone has time and need it, he can make a PR.

To be clear : I didn't say this is not needed, or it is a bad idea, but I just can't do it.
